### ISSUE TITLE
Not an issue but just a question (or two)...

### ISSUE THREAD

**Issue by SoftwareGuy** [pret/pokered#118]
With this disassembly, are you doing a 1:1 compatible build of the Pokemon Red/Blue ROMs?

For example if you play any of the built ROMs, will the game be identical to the retail ROM? Or do we have bug fixes that nerf some of the common glitches and other things like MissingNo?

I don't mind if we're doing a 1:1 replica of the classic game code, but bonus points if MissingNo and friends get nerfed.

**Comment by PikalaxALT** [comment]
This disassembly will build the original US release versions of Red and Blue with no alterations, assuming we don't screw it up.

**Comment by iimarckus** [comment]
That said, the disassembly is the easiest way to fix the bugs you mentioned, should you have any interest in doing so for your own purposes.
