### ISSUE TITLE
make: rgbasm: No such file or directory

### ISSUE THREAD

**Issue by WelkinXie** [pret/pokered#119]
I just follow the steps:

xcode-select --install
sudo easy_install pypng

git clone https://github.com/bentley/rgbds
cd rgbds
sudo make install
cd ..

git clone --recursive https://github.com/pret/pokered
cd pokered

make
.
.
.

But it happens as follow:

$ make
rgbasm -h -o red/audio.o red/audio.asm
make: rgbasm: No such file or directory
make: *** [red/audio.o] Error 1

**Comment by PikalaxALT** [comment]
That means rgbasm is not on your system path.  You should find out where rgbasm et al were installed, and append it to the system path (environment variable $PATH).  Alternatively, you can move those programs to a directory that's already in your system path.  We typically suggest installing the rgbds programs to /usr/local/bin/.

**Comment by WelkinXie** [comment]
Cheers!
