### ISSUE TITLE
Question: Changing Alphabet?

### ISSUE THREAD

**Issue by marbuljon** [pret/pokered#124]
Hey, I realize that to change the general in-game alphabet I just edit font.png, but how can I change which keys map to what when editing text/dialogue so I can ex. write ĉ in the text editor and ĉ appears in the game? (Instead of how it is now where I replace x with ĉ on font.png, then type x in the text editor in order to get ĉ).

**Comment by xCrystal** [comment]
Change the 'x' to a 'ĉ' in charmap.asm

**Comment by marbuljon** [comment]
Ah!!! Thanks a lot, I thought char stood for "character" (as in sprite etc.) for some reason so I didn't even think to look there.
