### ISSUE TITLE
Use Japanese Overlay Key?

### ISSUE THREAD

**Issue by marbuljon** [pret/pokered#125]
Hey, in the Japanese games the alphabet has assigned a special key so that if you press ° it'll overlay on top of the character and make ぱぴぷぺぽ as opposed to はひふへほ for example. I wanted to utilize this for my game, so that if I were to replace it and press ˆ I'd get ĈĜĤ. 

But I don't know how to: 
1. Access the Japanese alphabet and/or that special key in the first place (if even it exists in the English release?), 
2. change the key mapping in the text editor so that if I type ĉ it shows up as ĉ in-game (I've submitted a separate help request for that).

It could be that one of the many blank keys on the English alphabet layout is this special key, so I guess I can try looking at that first...

**Comment by Ratstail91** [comment]
This sounds suspiciously like a shift key.

**Comment by PikalaxALT** [comment]
The Japanese character map does not exist in the English release.  It sounds like you're talking about the dakuten, the code for which I believe still exists, unused, in home/text.asm.  You'll need to modify that function, the conditions under which it is called, and the character map (macros/charmap.asm) to get the effect you want.

**Comment by marbuljon** [comment]
I made a thread for it here and someone responded:
https://hax.iimarck.us/topic/6742/
