### ISSUE TITLE
Question - Green Version?

### ISSUE THREAD

**Issue by marbuljon** [pret/pokered#126]
Hey, do you guys have any plans for making this work with Green (or the Japanese games in general)? I want to make a Green hack but as it is now it means replacing the graphics, pallette, cave layout, and all the dialogue, and then anyone else who wants to do the same thing has to go through all the same trouble as me....

EDIT: nevermind, I found out someone's doing it!

**Comment by dannye** [comment]
If you are referring to fotomac, again he is misleading you. He is not disassembling the original Japanese Green rom and reproducing the source code. He is making a hack of English Red and making changes that make English Red resemble Japanese Green more closely.

Afaik, no one here currently plans on disassembling the original Japanese Green.

**Comment by iimarckus** [comment]
Nobody is currently working on it, but if someone were to start that would be really cool. Due to the differences in code layout compared to the international releases it would probably have to be a separate repository, like Yellow.

**Comment by marbuljon** [comment]
Oh okay, thanks!
