### ISSUE TITLE
Support for Yellow version?

### ISSUE THREAD

**Issue by ShadowOne333** [pret/pokered#127]
Good day.

I wanted to drop by and ask if there are some plans about giving Pokemon Yellow the same treatment as Red & Blue?
I would love to see the game in full colour along with many of the Gen II features.
I would surely give it a second run from scratch up to all the 151 Pokemon if it becomes available.

Thanks in advance!

**Comment by YamaArashi** [comment]
https://github.com/pret/pokeyellow

It is not yet fully complete.

**Comment by ShadowOne333** [comment]
Oh neat!
I didn't know you were already working on Pokemon Yellow.

I'll follow the project closely. 
Thanks!
