### ISSUE TITLE
Suggestion: Japanese Graphics?

### ISSUE THREAD

**Issue by marbuljon** [pret/pokered#128]
Hi, it would be really cool if we could somehow have the option of picking from the English or Japanese graphics. Seems like the Japanese Red and Green have different graphics compared to the Japanese Yellow, but the English Red uses the Japanese Yellow graphics. Check it out:

![skarmavbild 2016-03-12 kl 19 34 08](https://cloud.githubusercontent.com/assets/10114924/13724605/80b8805e-e88b-11e5-8628-a28e85adcdde.png)
![skarmavbild 2016-03-12 kl 19 37 37](https://cloud.githubusercontent.com/assets/10114924/13724607/87692cf0-e88b-11e5-922e-5856c8045db7.png)

The only things I've seen people talk about so far have been the pokemon battle sprites + the overworld flowers being different, but as the pictures show there's probably a lot more... 

EDIT: Maybe it's mostly just a mapping issue? It seems like the English Yellow actually uses some of the same graphics as the Japanese RBG, so I guess I'll be stealing stuff from pokeyellow!

**Comment by LIJI32** [comment]
There are 3 sets of tileset graphics in the Generation I core series game. The first set is used in the Japanese versions of Pokémon Red and Green. The second set is used by Japanese Blue and international Red and Blue. The third set is used by all versions of Yellow.

**Comment by SoftwareGuy** [comment]
If I remember correctly, don't the Japanese versions have different pokemon back and front sprites compared to the international releases? I know the US Yellow has different front and back for Ratatta and starter pokemon.

**Comment by LIJI32** [comment]
The back sprites are the same in all versions. For front sprites, there are 3 sets, as described above.

**Comment by pattraynor** [comment]
I am a tad unfamiliar in regards to emulators, but in regards to playing
this on an actual Gameboy flash cart, would there be enough memory
available to support this?

**Comment by iimarckus** [comment]
Given the way things have gone (pokered, pokeyellow, pokered-fr), it seems likely that someone will disassemble the Japanese versions at some point. Then maybe there will be some effort to unify the disparate repositories. Or maybe not… hard to predict the future.

**Comment by camthesaxman** [comment]
I think the Japanese versions of Red and Green have a lot of differences code-wise from the international versions, so it might warrant a separate repository. Similar to how there's a separate repository for yellow.

**Comment by YamaArashi** [comment]
I started on a repository for Japanese Red/Green but it needs a lot more work. https://github.com/YamaArashi/pokered-jp

**Comment by marbuljon** [comment]
Thanks a lot! By the time the disassembly is done, I'll probably be fluent in Japanese and will be able to do a real translation of it...

Should I close this thread?
