### ISSUE TITLE
Removing Missingno?

### ISSUE THREAD

**Issue by Tinymantwo** [pret/pokered#129]
I wondered if you will be removing Missingno. Also I can I test this game? I don't know how to convert it into a .gba game yet but thanks anyway

**Comment by dannye** [comment]
This does not remove missingno or fix any other bug.
If by "convert" you mean "compile" then just take a look at INSTALL.md

**Comment by Tinymantwo** [comment]
Yes by convert I did mean compile sorry I wasn't with it last night

**Comment by wolfboyft** [comment]
This is a disassembly that recompiles into the exact code that was disassembled. Unless you're going to be making a hack, the only modifications that are made in the main repositories are macros, label names and other things that don't affect the final ROM.

**Comment by wodim** [comment]
@wolfboyft will _Orc Goblins in Green Socks_ include Missingno? It could be a modified version of Bruce Willis, for example, Bruce Willis with a mullet.
