### ISSUE TITLE
[SOLVED] I can't build the ROMs

### ISSUE THREAD

**Issue by javidg96** [pret/pokered#149]
So, I've tried to build the ROM files but I seem to get an error.

> bash-4.4$ git clone --recursive https://github.com/pret/pokered
> Cloning into 'pokered'...
> remote: Counting objects: 22380, done.
> remote: Total 22380 (delta 0), reused 0 (delta 0), pack-reused 22380
> ects: 100% (
> Receiving objects: 100% (22380/22380), 11.84 MiB | 543.00 KiB/s, done.
> Resolving deltas: 100% (14763/14763), done.
> Checking connectivity... done.
> Checking out files: 100% (2847/2847), done.
> Submodule 'extras' (git://github.com/kanzure/pokemon-reverse-engineering-tools.git) registered for path 'extras'
> Cloning into '/usr/bin/pokered/extras'...
> remote: Counting objects: 4577, done.
> remote: Total 4577 (delta 0), reused 0 (delta 0), pack-reused 4577
> ts: 100%
> Receiving objects: 100% (4577/4577), 2.29 MiB | 546.00 KiB/s, done.
> Resolving deltas: 100% (2882/2882), done.
> Checking connectivity... done.
> Submodule path 'extras': checked out '0e1798937a4bf723813574281d0dc12c471c9199'
> bash-4.4$ cd pokered
> bash-4.4$ make
> rgbasm -D _RED -h -o audio_red.o audio.asm
> make: rgbasm: Command not found
> make: *** [Makefile:37: audio_red.o] Error 127
> bash-4.4$

I'm running 64-bit Windows 10. I've installed Cygwin on HDD E:\ , I've put the rgbasm files on the right directory and I believe I have set the var "Path" correctly. Any clues?

**Comment by rweichler** [comment]
its PATH not Path

**Comment by Sanqui** [comment]
Have you installed `rgbds`?

**Comment by javidg96** [comment]
@rweichler Didn't make a difference.

@Sanqui I went to check the environment vars and I didn't have it set up, so I did it myself. I set it up as **E:\Cygwin\bin**. Then I downloaded rgbds version **rgbds-0.2.4-win32** and I put the three executables at **E:\Cygwin\usr\local\bin**.

**Comment by jcebuck** [comment]
Did you add `E:\Cygwin\usr\local\bin` to your PATH too?

**Comment by javidg96** [comment]
@jcebuck Wow, I didn't think of that. It did compile now. The only problem I have now is the games don't actually have any sound when emulated. Feedback seems okay.

Log:
> bash-4.4$ cd pokered
bash-4.4$ make
rgblink -n pokered.sym -o pokered.gbc audio_red.o main_red.o text_red.o wram_red.o
rgbfix -jsv -k 01 -l 0x33 -m 0x13 -p 0 -r 03 -t "POKEMON RED" pokered.gbc
rgblink -n pokeblue.sym -o pokeblue.gbc audio_blue.o main_blue.o text_blue.o wram_blue.o
rgbfix -jsv -k 01 -l 0x33 -m 0x13 -p 0 -r 03 -t "POKEMON BLUE" pokeblue.gbc
bash-4.4$

**Comment by Sanqui** [comment]
I would like to know is `C:\Cygwin\usr\local\bin` is in the PATH by default, but `E:\Cygwin\usr\local\bin` is not.  Is this the case?

**Comment by javidg96** [comment]
@Sanqui It wasn't when I first installed it. As I already said, I went to check the variable, and I didn't have the var set yet. It just didn't add it for some reason.

As of now, what I've set as values are the following directories: **E:\Cygwin\bin** and **E:\Cygwin\usr\local\bin**.

**Comment by Vaporeon** [comment]
For anyone on Windows 10 I recommend trying the Windows Subsystem for Linux. As of the recent update it works really well and can be easier to set things up than Cygwin. Just enable it, run bash.exe and once in the shell follow the Linux guide on here.

**Comment by Eggbertx** [comment]
I'm not sure if they fixed it, but while that's mostly true, it does have some issues with ncurses and you can't set up servers (like node.js stuff) yet.

**Comment by javidg96** [comment]
Guys, while the topic is still active I'd like to ask something. Have you ever thought about decompiling other versions of the games in the future? You know: ESP, NOE, FAH...

I'd like to do a decent translation on the Spanish version so it can be compatible with the original one, since the strings would be the only modified part of the ROM. There would be two problems for this as of now. First, the resulting ROM would be compatible with the US version only. Secondly, this version lacks additional character support ('¿', '¡', 'ñ'...)

How complicated would this be? Is there a huge difference in the code as compared to the US versions? I know nothing about assembly reverse engineering, so if I'm asking for something overly intricate, just tell me.

**Comment by Sanqui** [comment]
@javidg96 Some people are working on disassembling the other versions, e.g. https://github.com/einstein95/pokered-fr.
However, this is not the right place to discuss this.
