### ISSUE TITLE
MBC Type?

### ISSUE THREAD

**Issue by Baekalfen** [pret/pokered#155]
I'm having trouble determining which MBC is officially used for these cartridges.

I can see from the disassembly, and from my own dumped Pokemon Blue, that it acts like an MBC1. But looking at the header data, at 0x0147, I find the value 0x13, indicating an MBC3 controller with SRAM and battery, but no RTC.

Have I overseen something, or is the value of 0x13 or my MBC table just incorrect?

**Comment by einstein95** [comment]
Why would you think that there's an RTC? That would be added in Gold/Silver.

**Comment by Sanqui** [comment]
The English versions of Pokémon Red and Blue have a MBC3, just like the ROM says.

There's also a photo over [here](https://gekkio.fi/files/gb-cartridges/DMG-KFDN-01.DMG-APEE-USA.front.jpg) ([source](https://gekkio.fi/blog/2016-03-19-game-boy-cartridge-pcb-photos.html)).

**Comment by Sanqui** [comment]
The Japanese versions indeed had a MBC1.

MBC3 [behaves similarly](http://gbdev.gg8.se/wiki/articles/Memory_Bank_Controllers#MBC3_.28max_2MByte_ROM_and.2For_32KByte_RAM_and_Timer.29) in some ways to MBC1.

**Comment by Baekalfen** [comment]
I guess it must be the MBC3 then.

But something still seems a bit strange to me. I can see in `main_menu.asm` under `CheckForPlayerNameInSRAM`, that the code tries to change banking mode just like MBC1 (and actually naming it MBC1).

This seems to conflict with the sources I can find on MBC3, where non of them describe any banking modes. Could this simply be leftover code from the Japanese version, which has no effect on the non-RTC MBC3?

**Comment by Sanqui** [comment]
The MBC1 constants are defined in [hardware_constants.asm](https://github.com/pret/pokered/blob/46a94c63fc287e7290502776d02648476bc44171/constants/hardware_constants.asm#L5) and are arguably a misnomer from us.  The addresses to bankswitch and enable/disable SRAM are the same between MBC1 and MBC3.

**Comment by Baekalfen** [comment]
All true. What I'm puzzled by, is the write of 1 and later 0 to `MBC1SRamBankingMode` (0x6000), which is supposedly undocumented for this MBC.

I guess the conclusion is, that it need not be there, as it doesn't affect the MBC.

Thanks for your time anyway :)

**Comment by Sanqui** [comment]
Ah, good catch.  `MBC1SRamBankingMode` is indeed a MBC1 leftover and is meaningless in the international versions.

You're welcome.
