### ISSUE TITLE
Make failed: Section 'Stack' is too big

### ISSUE THREAD

**Issue by danielricks** [pret/pokered#157]
I followed the instructions exactly, and it gives me this error.

![screenshot from 2017-04-28 14 01 05](https://cloud.githubusercontent.com/assets/2449536/25545245/230a9102-2c1b-11e7-9d83-d32e4264ea5c.png)

Also the install instructions don't mention that flex has to be installed. 'sudo apt-get install flex' worked though.

**Comment by yenatch** [comment]
I believe this is caused by the lone `ds -$100`. This was a bit of a hack to begin with so I've removed it.

pokered is not compatible with rgbds 0.3.0 yet. I have amended INSTALL.md to use 0.2.5.

**Comment by danielricks** [comment]
Yeah that fixed it. Thanks.
