### ISSUE TITLE
Use macros for warps/signs

### ISSUE THREAD

**Issue by yenatch** [pret/pokered#159]

**Comment by huderlem** [comment]
It seems that macros for warps and signs will essentially just replace the "db" in their current form.  I could see there being another macro for warps that take you to the previous map, denoted by $FF as the destination map id.

I would implement these macros like so:

## Normal Warp
Current Form:
`db <y>, <x>, <destination-warp-id>, <destination-map-id>`
Macro:
`warp <y>, <x>, <destination-warp-id>, <destination-map-id>`

## Previous Map Warp
Current Form:
`db <y>, <x>, <destination-warp-id>, $FF`
Macro:
`warp_back <y>, <x>, <destination-warp-id>`
Not sure about the name `warp_back`.  Other ideas would be `warp_out` and `warp_previous_map`.

## Signposts
Current Form:
`db <y>, <x>, <text-id>`
Macro:
`sign <y>, <x>, <text-id>`

Does this sound ok to others?  I believe that macros will help with readability here, but they won't do much in terms of simplifying the underlying data structure, like most other macros.

**Comment by yenatch** [comment]
Swap x and y.

For `warp_back`, you could do `warp x, y, w` and autofill -1:
```asm
warp: macro
if _NARGS >= 4
    db \2, \1, \3, \4
else
    db \2, \1, \3, -1
endif
endm
```

**Comment by huderlem** [comment]
I definitely agree with switching `x` and `y`.  I do think a separate `warp_back` macro is a little better, due to readability.  If you're unfamiliar with warps, it's not obvious what it means when you see `warp x, y, map`.  `warp_back` gives a hint about what it means.  (Looking back now, I like `warp_back` the most out of the 3 names in the first post.)

**Comment by huderlem** [comment]
And of course, swap `x` and `y` for the `sign` macro, too.

**Comment by yenatch** [comment]
everything but `warp_back` is covered by #174

**Comment by Rangi42** [comment]
IMO `warp_back` is not worth adding; `warp` with some `PREVIOUS_MAP EQU -1` constant is also clear, and would be less of a special case for potential mapping tools to handle.
