### ISSUE TITLE
Sound and Battles are broken

### ISSUE THREAD

**Issue by knuxyl** [pret/pokered#160]
The only sounds working correctly are Professor Oak song while choosing name and such and pokemon cries. The rest are either playing the wrong songs, wrong speed, or just aren't present.

The first battle with Gary glitches after first attack, taking forever to load, not continuing, etc. 

This is the current build.

I also noticed that there were warning signs during make about jp [hl] and [sp + 0] being obsolete, so i wrote a script to fix them, although this does not fix the problems listed above.

```
find . -name "*.asm" -exec sed -i -e 's/jp \[hl\]/jp hl/g' {} \;
echo "Done fixing jp hl"
find . -name "*.asm" -exec sed -i -e 's/\[sp + 0\]/sp+0/g' {} \;
echo "Dont fixing sp+0"
```

**Comment by huderlem** [comment]
What version of RGBDS are you using?  I just confirmed that everything builds correctly and outputs the correct ROM, so nothing is broken.

**Comment by knuxyl** [comment]
This seems to be caused by newer versions of rgbds, I got 0.2.5 and no more problems.
```
#!/bin/bash
echo "Installing Dependencies..."
sudo apt-get install byacc flex pkg-config libpng-dev
echo "Done installing dependencies"
echo "Cloning pret pokered..."
git clone --recursive https://github.com/pret/pokered
echo "Done cloning"
echo "Cloning rednex rgbds..."
git clone --recursive https://github.com/rednex/rgbds
echo "Done cloning"
cd rgbds
echo "Building rgbds v0.2.5..."
git checkout v0.2.5
make
cp rgb* ../pokered
echo "Done building"
cd ../pokered
echo "Fixing makefile so rgbds doesn't have to be installed..."
cat Makefile | sed 's/rgb/\.\/rgb/g' > Makefile2
mv Makefile Makefile.bak
mv Makefile2 Makefile
echo "Done fixing"
echo "Building pokered..."
make
echo "Done building"
```

**Comment by huderlem** [comment]
Yes, 0.2.5 is the currently-supported version for building pokered, as mentioned in the installation instructions.  I'm not familiar with the recent updates to RGBDS, but I imagine this repo will be snapping to the latest version sometime in the not-too-distant future.
