### ISSUE TITLE
Compiling with cygwin

### ISSUE THREAD

**Issue by ChelleBell** [pret/pokered#161]
While trying to compile in cygwin, I get the following error:
ERROR: wram.asm(3146):
        Constant mustn't be negative: -2
make: *** [Makefile:46: wram_red.o] Error 5

However, I haven't actually made any changes to this file, especially not anything related to that particular line, so I'm unsure of what would be causing it.

**Comment by yenatch** [comment]
You need rgbds 0.2.5: https://github.com/bentley/rgbds/releases/tag/v0.2.5

If you still get errors, you probably need to run `make clean` and then `make` again.

**Comment by ChelleBell** [comment]
Downgrading my rgdbs just gives me the "'audio_red.o' is an unsupported version" error that everyone seems to indicate means rgdbs needs to be upgraded.

So I reupgraded to rgbds 3.2, recloned pokered, then ran make clean and make red... no dice. Still getting the same error as before.

**Comment by einstein95** [comment]
As @yenatch said, downgrade to 0.2.5, run `make clean` and then `make`.

**Comment by ChelleBell** [comment]
So, as it turns out, I am bad at interpreting the English language. Downgrading and then not upgrading like a fool solved my problem. Gonna go ahead and close this now.
