### ISSUE TITLE
Queston

### ISSUE THREAD

**Issue by TheRealPiggyWiggy** [pret/pokered#164]
Can some one make an updated version on how to ad genders

**Comment by minirop** [comment]
I don't think that would be possible. It would be probably preferable to redo pokered (maps, scripts, events, etc.) inside pokecrystal.

**Comment by dannye** [comment]
It is possible. Whether you are talking about adding genders for the player character or for Pokemon, both have been done in pokered.

**Comment by TheRealPiggyWiggy** [comment]
Adding genders for trainers
