### ISSUE TITLE
Rename PSYCHIC to PSYCHIC_TYPE

### ISSUE THREAD

**Issue by huderlem** [pret/pokered#165]
People often forget or aren't aware of the difference between PSYCHIC and PSYCHIC_M. 

This would prevent someone from using the wrong PSYCHIC constant.

**Comment by huderlem** [comment]
Potentially add _TYPE suffix to all type constants.

**Comment by yenatch** [comment]
or prefix

**Comment by Rangi42** [comment]
Tracked in #249.
