### ISSUE TITLE
Mac Install Error: SHA256 mismatch

### ISSUE THREAD

**Issue by marbuljon** [pret/pokered#176]
Upon trying to install rgbds on a Mac I get this:

==> Installing dependencies for rgbds: libpng
==> Installing rgbds dependency: libpng
==> Downloading https://downloads.sourceforge.net/libpng/libpng-1.6.34.tar.xz
==> Downloading from https://downloads.sourceforge.net/#!/libpng/libpng-1.6.34.t
######################################################################### 100.0%
Error: SHA256 mismatch
Expected: 2f1e960d92ce3b3abd03d06dfec9637dfbd22febf107a536b44f7a47c60659f6
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/(USERNAME)/Library/Caches/Homebrew/libpng-1.6.34.tar.xz
To retry an incomplete download, remove the file above.

—————
I removed the file and retried, but get the same error every time.

**Comment by yenatch** [comment]
you should report this to the rgbds maintainers https://github.com/rednex/rgbds/issues

for now just build it from source https://github.com/rednex/rgbds/blob/master/README.rst#building-rgbds-from-source

**Comment by marbuljon** [comment]
Thanks. The "2. Building RGBDS from source" instructions say:
brew install libpng pkg-config

There I get the exact same error as before.

**Comment by yenatch** [comment]
try `brew update`. https://docs.brew.sh/Troubleshooting if that doesnt work its likely an issue with the brew package listing for libpng, or the download was compromised

**Comment by marbuljon** [comment]
Thanks, in the end it was a problem with Homebrew and I downloaded the messed-up package from an external site and put it into the folder myself and installing rgbds seemed to work fine. Then I tried to install pokered and it seemed to work fine... and then I tested the "make" command and got this error:

rgbasm -D _RED -h -o audio_red.o audio.asm
rgbasm -D _RED -h -o main_red.o main.asm
rgbasm -D _RED -h -o text_red.o text.asm
rgbasm -D _RED -h -o wram_red.o wram.asm
rgblink -n pokered.sym -l pokered.link -o pokered.gbc audio_red.o main_red.o text_red.o wram_red.o
rgblink: illegal option -- l
usage: rgblink [-t] [-m mapfile] [-n symfile] [-o outfile] [-p pad_value]
               [-s symbol] file [...]
make: *** [pokered.gbc] Error 1
