### ISSUE TITLE
Lowercase HRAM constants

### ISSUE THREAD

**Issue by xCrystal** [pret/pokered#186]
Some still have the H_* format. wram, vram and sram are good.

**Comment by dannye** [comment]
This is handled by PR #166 but there are other changes in there that might not be a good idea, so maybe one of us should redo this aspect in its own PR

**Comment by xCrystal** [comment]
Ah, didn't see that PR. Whether they are H_UPPERCASE constants or hCamelCase ds offsets I don't mind, but they should all have the same format (actually, I would put them as camel case even if they were hardcoded because in practice you're using them similarly to wram addresses even if they're declared differently).
I don't even have a clear pokered repo locally at the moment so I guess it would be faster if done by someone else that does, considering that it's just some trivial find/replace.
