### ISSUE TITLE
Error compiling engine/menu/party_menu.asm with rgbasm v0.3.7

### ISSUE THREAD

**Issue by marespiaut** [pret/pokered#197]
I've tried to `make blue` and `make red` using rgbds v0.3.7 and the latest git revision, and I get the following error message:

```
rgbasm -D _RED -h -o main_red.o main.asm
ERROR:	main.asm(193) -> engine/menu/party_menu.asm(153) :
	syntax error
rgbasm: Assembly aborted in pass 1 (1 errors)!
make: *** [Makefile:58: main_red.o] Error 1
```

**Comment by aaaaaa123456789** [comment]
`wEvosMoves.end` is at fault here. This isn't supported by RGBDS; someone must have been using a custom extension while writing this code.

**Comment by ISSOtm** [comment]
According to the RGBDS 0.3.2 changelog, this is supposed to be possible:
`Child labels can be referenced outside their scope through the parent label, even from other files (if they are made global).`
Refer to https://github.com/pret/pokered/blob/master/wram.asm#L1250-L1251, the labels are made global.

**Comment by marespiaut** [comment]
Hello,

This was my mistake here.

Apparently I've installed an old version of RGBDS a long time ago, an my package manager, despite claiming it was successful, never updated it.

So I had some old 0.?.? binaries registered as 0.3.7 in the package manager database.
