### ISSUE TITLE
Change Oak Lab Coordinates in Pallet

### ISSUE THREAD

**Issue by ChefFloyardee** [pret/pokered#202]
Hello!

I changed the map of Pallet, and with it Oak's lab and warps.

I then changed how Oak leads Red to the lab in npc movement, so I can enter the lab's new location.

However, when I enter Oak is nowhere to be found, and I cannot move off of the entrance tile in the lab.

What else do I need to change?

My guess is the bolded line;

RLEList_ProfOakWalkToLab:
	db NPC_MOVEMENT_DOWN, $05
	db NPC_MOVEMENT_LEFT, $01
	db NPC_MOVEMENT_DOWN, $05
	db NPC_MOVEMENT_RIGHT, $03
	db NPC_MOVEMENT_UP, $01
	**db $E0, $01 ; stand still**
	db $FF

But I am unsure as to how to read those (coordinates?) numbers in the bolded line. This is from the npc movement asm file. 

Please help me if you can :D

**Comment by iimarckus** [comment]
This issues section isn’t for this kind of help; it’s to report problems with the disassembly itself. For questions like yours, try asking in the pret Discord or perhaps a forum.
