### ISSUE TITLE
Issues Adding 153+ Pokemon

### ISSUE THREAD

**Issue by ChefFloyardee** [pret/pokered#203]
Hello,

I am currently working on a hack of Pokemon Red, and I am trying to
add a 153rd mon.

I followed the Leafeon tutorial found in Danny-E's git, and my 152nd
mon works fine.

Here is the link to that tutorial.

https://github.com/pret/pokered/commit/c7ce0a95184784f029779426611324ff84f2ef12

I then did the same with his adding Glaceon tutorial, and everything
about mon #153 works fine except for the sprite. It gives me a
missingno sprite no matter what I do.

I feel as though I have triple-checked everything and exhausted all
alternate options available on the web, so I was wondering if one of
you could help me out (being as though you all seem to be Pokemon
hacking experts!)

**Comment by Asday** [comment]
Not that I'll be able to help you, but it will probably be easier for those who can for you to post a non-working code example.  Good luck!

**Comment by ChefFloyardee** [comment]
Which particular part of my code should I post?

**Comment by Asday** [comment]
Most useful would probably be something like the simplest possible 152nd added Pokemon (that works), then the simplest possible 153rd addrd Pokemon (that doesn't work).

You might even find that - in creating the [SSCCE](http://sscce.org/) - you solve your own problem, by breaking it down into something simple.

Like I said though, I won't be able to help you, so I won't be able to give you examples and such.  You know a lot more than me!  :)

**Comment by ChefFloyardee** [comment]
Here is a pastebin of my home and main asm files if that helps!
Home
https://pastebin.com/WXaUDg6C

Main
https://pastebin.com/RFDKjkCN
