### ISSUE TITLE
Text Speed Stuck on Medium, Battle Animations Stuck to Off - Issue/Glitch

### ISSUE THREAD

**Issue by ChefFloyardee** [pret/pokered#204]
Hi all!

When I compiled a fresh copy of the ROM for some reason the Blue Version's Options are stuck on Medium Speed, No Battle Animations, and Set.

When I change them back and close out, they just go back to these settings.

The Red Version works fine though, which is odd.

Perhaps this is a wram shifting issue? If so, how can I fix it? I am not sure, but I am hopeful one of you will!

Thanks!

**Comment by Pokechu22** [comment]
What's the md5 of the compiled rom?  It should be `50927e843568814f7ed45ec4f944bd8b`.  (`make compare` should check that these match)

**Comment by ChefFloyardee** [comment]
When I do make compare I get this.

Chase@Chase-PC ~/pokered
$ make compare

pokered.gbc: FAILED
pokeblue.gbc: FAILED
md5sum: WARNING: 2 computed checksums did NOT match
make: *** [Makefile:32: compare] Error 1

**Comment by dannye** [comment]
Make sure you have installed rgbds v0.3.8
Make sure `git log -1` shows "Merge pull request #201 from SatoMew/master"
Make sure `git status` shows no local changes
Do a `make clean` before `make compare`

Let me know if the compare still fails.

**Comment by ChefFloyardee** [comment]
I feel like a total idiot :P

I had my gameshark cheats on, but when I turned them off all works fine.

I don't know why they were causing those bugs though...hmmm....now I have a new issue though. I moved the Route 22 Rival Battle to Digletts Cave 1F, but when my rival comes to battle me he always says his "after battle" text before and after the fight.

It seems like the event that he is beaten is not getting recognized.

**Comment by ChefFloyardee** [comment]
I also just did some traveling in the game, and it thinks I beat all Elite 4 members....I do not know what is going on....

**Comment by dannye** [comment]
That sounds like save file corruption. Make sure you're not using a save file that came from playing a mod to pay vanilla red, or vice versa.

**Comment by ChefFloyardee** [comment]
I just deleted my pokered.sav file but no change occurred.

I am so close to releasing my beta, and these are the main issues remaining;
The Rival Battle I moved from Route 22 to Digletts Cave 1F works but the Rival always says the "before" battle message, before and after the fight.

The Elite 4 members do not fight me, nor do the Indigo Plateau guards stop me from moving.

Should I also delete my .sgm files?

**Comment by ChefFloyardee** [comment]
It's not working in the sister ROM either (so neither Blue or Red work).

**Comment by ChefFloyardee** [comment]
I just committed and pushed my latest changes to my git, so hopefully you'll be able to see what I screwed up!

**Comment by Asday** [comment]
(Which is at https://github.com/ChefFloyardee/pokefloyd, not https://github.com/ChefFloyardee/pokered).

**Comment by ChefFloyardee** [comment]
https://github.com/ChefFloyardee/pokefloyd,

Yes, this one

**Comment by ChefFloyardee** [comment]
I use Visual Boy Advance to work on my ROM, and I use the Gameshark codes to make things easier to test.

I noticed after my commit 4 days ago though that when I had the codes on my text speed was stuck to medium and my battle animations were turned off (neither would turn back on without the hceats being off).

I can also no longer use the "all 8 badges" code. 

But my main issue is this; I moved the Route 22 Rival battle to Digletts Cave 1F, and it works but the "after" battle message always reads before and after the fight.

I also walked through walls up to the Indigo Plateau to do some tests, but none of the Elite 4 will fight me for it says I already beat them.

**Comment by ChefFloyardee** [comment]
Ideally I could fix the Rival text issues, regain the use of the "all 8 badges code", and reactivate the Elite 4 to allow me to finish the beta parts of my hack.

**Comment by ChefFloyardee** [comment]
Here are my latest commits;

https://github.com/ChefFloyardee/pokefloyd/commit/753c6c3bcc2fd1e82fcfd2eee9768aebba7e1ad7

**Comment by ChefFloyardee** [comment]
So I did some more tests, and when I noticed this.

When I have one badge, the Elite 4 do not work and will not fight me.

With no badges they work fine.

The rival Route 22 issue continues though.

Why does it flag me as having all of the Elite 4 defeated after I get one badge?
