### ISSUE TITLE
ROM Thinks Elite 4 is Beaten + Hide/Show Not Working

### ISSUE THREAD

**Issue by ChefFloyardee** [pret/pokered#205]
I have 3 issues that I need help with;

First, I moved the Route 22 Battle to Diglett's Cave 1F, but every time I battle the rival he says his "after battle" text before and after the fight. So it seems like the game thinks I already beat him, despite retriggering the fight.

Second, after getting only 1 Badge and then going to the Elite 4 via walk through walls (for test purposes) none of the E4 will fight me and they act as if I already beat them. So this also seems like it is already flagged as beaten for some reason.

Third, I tried moving Giovanni's "fade to black then disappear" feature to Lance, but it is not working as well. I followed this guide (https://hax.iimarckus.org/topic/7574/) to no avail.

Please let me know if any of you can help me!

**Comment by Tauwasser** [comment]
Honestly, this sound like you have an issue with some other code overwriting the RAM where these flags are stored. What else did you change?

**Comment by ChefFloyardee** [comment]
"Cave" and "E4" are my most recent two commits.

https://github.com/ChefFloyardee/pokefloyd/commits/master

Do you also have any clue about how to make Lance disappear ala Giovanni after being defeated? I tried to code (see the E4 Commit) it but it is not working.
