### ISSUE TITLE
No Constant to Start Champion Rival Battle

### ISSUE THREAD

**Issue by ChefFloyardee** [pret/pokered#207]
I'm trying to figure out what controls the Final Elite 4 fight versus the Champion Rival and I noticed that there is no constant in Event Constants to trigger this fight or to auto-walk up to the Rival.

The other Elite 4 Rooms have this (Lance does not have the auto-walk either for some reason), so I was wondering if this would be a good idea for something that should be added to Pokered to help make it clearer as to what controls this.

Please let me know!

**Comment by CelestialAmber** [comment]
The constant needed to be set is wChampionsRoomCurScript, which controls the current script to execute in the Champion's room map. By default, it's 0, which results in nothing happening: https://github.com/pret/pokered/blob/725b86ebbec23bd1f53fd60bf0201c904fee951d/scripts/ChampionsRoom.asm#L26.
It needs to be 1 to allow the final battle to happen, which is set after beating Agatha.

**Comment by ChefFloyardee** [comment]
Interesting!

Why is this set after Agatha, and not Lance?

Also, how would one change Lance's script to set this instead?
