### ISSUE TITLE
Generating a template produces a nonmatching build.

### ISSUE THREAD

**Issue by luckytyphlosion** [pret/pokered#222]
For some reason, reds_house.tilecoll is two bytes larger when pokered is generated from a template.
- [pokered](https://github.com/pret/pokered/blob/master/gfx/tilesets/reds_house.tilecoll)
- [pokered-template](https://github.com/luckytyphlosion/pokered-template/blob/master/gfx/tilesets/reds_house.tilecoll)

This might be related to the fact that Github sees those files as plaintext and not binary.

**Comment by PikalaxALT** [comment]
IMO this issue is no longer relevant, as we've abandoned the template feature.

**Comment by dannye** [comment]
Also, (and this is more circumstantial) the particular binary file causing the issue no longer exists.
