### ISSUE TITLE
Swapping the bmon and rgmon folders does not work

### ISSUE THREAD

**Issue by DJLoogie** [pret/pokered#230]
So I was gonna try and play this hack using the rgmon folders sprites so I simply renamed them both and it actually causes this unique error that I have taken a screen shot of.. I can only get this error with this hack weirdly, is there any solution to this so I can play this hack with the rg sprites?
![~_shinpokered-master 11_25_2019 1_20_51 PM](https://user-images.githubusercontent.com/55605193/69567013-6ef7f680-0f86-11ea-976b-6975fcf5b9eb.png)

**Comment by Alchav** [comment]
The way the sprites have compressed for this particular bank is making them larger files than the R/B sprites and they aren't fitting. You would have to shift sprites into other banks in main.asm and update the sprite mapping code in UncompressMonSprite in engine/home.asm

**Comment by Alchav** [comment]
I went ahead and made my own fork to accomplish this
https://github.com/Alchav/pokered.git
