### ISSUE TITLE
where to start disasm?

### ISSUE THREAD

**Issue by arathron** [pret/pokered#231]
Hi,
I would love to disasm some gameboy roms.  I'm particularly interested in Final Fantasy Adventure.
I can run mgbdis v1.3 and then assemble the rom again, but after that I don't know where to start.
Can I legally upload these bank_00*.asm files to github? And ask for help from there?
Where should I search for graphic data? (I only see assembler code in those files)
Thanks,
Damián

**Comment by luckytyphlosion** [comment]
This page only concerns issues regarding the pokered disassembly project itself. If you want pointers on how to start your own disassembly, you can find help in the pret discord, link in the readme.
