### ISSUE TITLE
Sync with pokeyellow

### ISSUE THREAD

**Issue by dannye** [pret/pokered#240]
Now that pokeyellow has been synced with pokered, pokered needs to be synced with pokeyellow for a few miscellaneous things.

Over the years, contributors have made improvements to pokeyellow that were not strictly pokeyellow exclusive. These improvements should be ported to pokered as well.

Here is a non-exhaustive list of the most obvious things:
- [x] Credits command constants (constants/credits_constants.asm and data/credits_order.asm)
- [x] `hidden_object` macro
- [x] Offset arithmetic into `wSpriteStateData1` (and probably other related structs)
- [x] Lots of labels, constants, and comments in engine/remove_pokemon.asm
- [x] Logical spacing in data/super_palettes.asm
- [x] New HRAM labels like `hDidntFindAnyHiddenObject` (and maybe others)
- [x] Inconsistent use of `BANK()` versus `Bank()`

There are several other more minor differences as well. There are a fair number of whitespace differences, particularly with comma separated lists or padding around arithmetic operators.

[This diff page](https://github.com/dannye/pokeyellow/compare/pokered...master#files_bucket) can be used to help spot these areas of improvement.

**Comment by Rangi42** [comment]
Reminder to refer to pokeyellow while reorganizing pokered. (After which a lot will need syncing *to* pokeyellow.)

**Comment by Rangi42** [comment]
PR #259 applies the particular things listed above. There will still be various whitespace and labeling differences with pokeyellow, but those should probably be reviewed *after* re-syncing pokeyellow to pokered's new file structure.

**Comment by dannye** [comment]
Wow, thanks!
