### ISSUE TITLE
Possible incorrect comments in Trainer AI file regarding switching?

### ISSUE THREAD

**Issue by invalio19** [pret/pokered#244]
Apologies if I'm incorrect here but I think there are some misleading comments in the Trainer AI file regarding switching out.

The comments appear to indicate that the enemy Trainer will only switch if they have at least 3 non-fainted Pokémon in their party. I believe this should say 2, not 3.

I have tested in-game against the first Juggler to the west of Fuchsia Gym. This Trainer has only two Pokémon (Drowzee and Kadabra) and still switches between the two very often.

The lines I'm using for reference read:

	ld a, d ; how many available monsters are there?
	cp 2 ; don't bother if only 1 or 2
	jp nc, SwitchEnemyMon

Now my knowledge of assembly is extremely limited at best, but I believe that the carry flag is reset here if 'a' (number of available mons) is greater than OR EQUAL to 2.

Also affects pret/pokeyellow.

File: engine/battle/trainer_ai.asm
Comment: engine/battle/trainer_ai.asm#L651
Comment and code: engine/battle/trainer_ai.asm#L675

**Comment by dannye** [comment]
Yes, I think you are correct.
