### ISSUE TITLE
Rename text_linkpromptbutton

### ISSUE THREAD

**Issue by Rangi42** [pret/pokered#260]
The current text command names were previously discussed for pokecrystal: https://github.com/pret/pokecrystal/issues/575

`text_linkpromptbutton` corresponds with `text_promptbutton` and pokecrystal's `promptbutton` script command, but it's an awkward name. @dannye @mid-kid any suggestions?

**Comment by dannye** [comment]
My first thought is renaming `text_linkpromptbutton` to `text_waitbutton`.
It behaves like `text_promptbutton` but without the visual prompt.

**Comment by Rangi42** [comment]
Is there definitely no visual prompt? `TextCommand_LINK_PROMPT_BUTTON` calls `ManualTextScroll` calls `WaitForTextScrollButtonPress` calls `HandleDownArrowBlinkTiming`.

Also, in pokecrystal, `text_waitbutton` was the previous name for `text_promptbutton`. It was renamed to correspond to the `promptbutton` event. (At that time, `text_linkpromptbutton` was `link_wait_button`.) (pokecrystal's `waitbutton` event command waits for an A or B press, with no arrow and no sound effect.)

**Comment by dannye** [comment]
> Is there definitely no visual prompt?

Yes. The easiest location to confirm is `ClosedOaksPCText`.

**Comment by Rangi42** [comment]
You're right. And `text_linkpromptbutton` is an unused leftover in pokecrystal.

I'm okay with `text_waitbutton`. The pokecrystal renaming was back in 2018, so people aren't likely to get confused. And it wouldn't be the first time we've had a rename conflict: `loadvar` became `loadmem`, and `writecode` became `loadvar`. (Although that still has legacy support: `loadvar` checks if it was passed a `VAR_` constant or a memory address.)

Just waiting to see what @mid-kid thinks.

**Comment by Rangi42** [comment]
I'm PRing `text_waitbutton` for now, but what do you think of `text_promptbutton_noblink` or `text_promptbutton_noarrow`?

**Comment by dannye** [comment]
Those are okay too but I don't think it needs to be that verbose.
