### ISSUE TITLE
NPC's Pokemon AI moveset

### ISSUE THREAD

**Issue by DudeNin64** [pret/pokered#266]
Is there anyway to change the moveset of NPC's pokemon?
For example, let's say the rival has a Lv. 65 Ninetales with Roar, Quick Attack, Ember, and Tail Whip, and I want to change those moves for Flamethrower, Body Slam, Dig and Toxic.

Is this possible?

**Comment by Rangi42** [comment]
The pret projects are meant to produce 100% accurate copies of the original ROMs. For that purpose, changing movesets or anything else is impossible.

If you're making your own pokered-based project, please ask questions in #pokered on [Discord](https://discord.gg/d5dubZ3).
