### ISSUE TITLE
"Couldn't write file - Permission Denied"

### ISSUE THREAD

**Issue by MoriyaFaith** [pret/pokered#291]
I was editing asm files, building, and things went entirely fine. However, when I tried building after editing the player front sprite and backsprite, I get this error message.
```
rgbasm -h -L -Weverything -D _RED -o gfx/pics_red.o gfx/pics.asm
error: Couldn't write file 'gfx/pics_red.o': Permission denied
make: *** [Makefile:89: gfx/pics_red.o] Error 1
```
It seems the file it isn't looking for just isn't there when I know I've seen those files before. Is this a problem with Cygwin, or the Dissasembly itself? I tried to boot up Cygwin in Adminstrator, and that didn't work. Any idea on what's going on here?

**Comment by MoriyaFaith** [comment]
Approximately 5 Minutes after reporting this, I figured out the problem. I set the files to being hidden, which is why I didn't see them in the first place. It hadn't needed to write to the files before I started editing graphics, which is why it never caused errors before.

**Comment by Sanqui** [comment]
Glad you got it figured out.  For next time, it would be best if you asked such quick support questions on the [Discord](https://discord.gg/d5dubZ3) instead!
