### ISSUE TITLE
modify the install instructions in install.md

### ISSUE THREAD

**Issue by gogo2464** [pret/pokered#296]
The build instructions for linux / ubuntu are wrong.

Currently when I built pokered with `make` I can see the error:

```
rgbasm -o rgbdscheck.o rgbdscheck.asm
ERROR: rgbdscheck.asm(11):
    pokered requires rgbds $0.$4.$1 or newer.
Makefile:72 : la recette pour la cible « rgbdscheck.o » a échouée
make: *** [rgbdscheck.o] Erreur 1
```

because I followed [these instructions](https://github.com/pret/pokered/blob/d44c7c305c3f94b59e3e2c008408779836a0020a/INSTALL.md#linux).

To solve this issue we have to write:

```
To install the software required for pokered:

sudo apt-get install make gcc git

To install rgbds:

sudo apt-get install pkg-config flex bison libpng-dev
git clone --depth=1 https://github.com/rednex/rgbds
sudo make -C rgbds install
```

instead of:

```
To install the software required for pokered:

sudo apt-get install make gcc git

To install rgbds:

sudo apt-get install pkg-config flex bison libpng-dev
git clone -b v0.4.0 --depth=1 https://github.com/rednex/rgbds
sudo make -C rgbds install
```

As you can see I removed `-b v0.4.0`. It does not give a stable version of rgbds but the latest. It even sounds better for me because rgbds is stably developped now.

Then I suggest to modify the install instructions from install.md to get something working.

**Comment by ISSOtm** [comment]
To get the latest release, use the `release` branch; better just link to https://rgbds.gbdev.io/install anyways.

**Comment by gogo2464** [comment]
@ISSOtm I do not need it. I have already everything working. I just open an issue to make a better project.
