### ISSUE TITLE
New Wiki page for Adding New Maps to the Game

### ISSUE THREAD

**Issue by mattcit** [pret/pokered#305]
I created an MD file that explains how to add new maps into the game, specifically what all .asm files need edited to add a new map into the game. Let me know if you want me to send it (I'm new to Github so I'm not sure of the correct ways to contribute).

**Comment by Pokechu22** [comment]
To create a new wiki page, go to the Wiki tab ([here](https://github.com/pret/pokered/wiki)) and click the green "new page" button.  Then, enter a title and paste the contents of your MD file into the body.  (GitHub wikis default to markdown, so everything should be formatted correctly).  Once the page is created, edit the [tutorials](https://github.com/pret/pokered/wiki/Tutorials) page to link to your new page (for instance, to link to `https://github.com/pret/pokered/wiki/Wild-encounter-slots`, you write `- [Link text](Wild-encounter-slots)`).

**Comment by mattcit** [comment]
Got it, I believe I added it successfully, thanks for the help!!
