### ISSUE TITLE
Cant Make...

### ISSUE THREAD

**Issue by Torombolo00** [pret/pokered#307]
Using windows 10 and WSL2/ Ubuntu

i get this error over and over, ive used the instructions over on the install.md 

    `torombolo@DESKTOP-6F9743O:~/poke/pokered$ make
    make: Entering directory '/home/torombolo/poke/pokered/tools' gcc -O3 -std=c99 -Wall -Wextra -pedantic -o scan_includes 
    scan_includes.c gcc -O3 -std=c99 -Wall -Wextra -pedantic -o gfx gfx.c gcc -O3 -std=c99 -Wall -Wextra -pedantic -o 
    pkmncompress pkmncompress.c make: Leaving directory '/home/torombolo/poke/pokered/tools'
    rgbasm -o rgbdscheck.o rgbdscheck.asm
    make: execvp: rgbasm: Permission denied
    make: *** [Makefile:72: rgbdscheck.o] Error 127
    torombolo@DESKTOP-6F9743O:~/poke/pokered$ sudo make red
    
    rgbasm -o rgbdscheck.o rgbdscheck.asm
    make: rgbasm: Command not found
    make: *** [Makefile:72: rgbdscheck.o] Error 127
    torombolo@DESKTOP-6F9743O:~/poke/pokered$ sudo make
    
    rgbasm -o rgbdscheck.o rgbdscheck.asm
    make: rgbasm: Command not found
    make: *** [Makefile:72: rgbdscheck.o] Error 127
    torombolo@DESKTOP-6F9743O:~/poke/pokered$`

Thanks!

**Comment by Rangi42** [comment]
Please ask for support in the pret `#pokered` [Discord](https://discord.gg/d5dubZ3); GitHub issues are for problems or to-dos with pokered itself.
