### ISSUE TITLE
Interesting quirk (bug?) with CooltrainerFAI

### ISSUE THREAD

**Issue by invalio19** [pret/pokered#308]
I noticed while playing Pokémon Red that CooltrainerF would repeatedly switch out her Pokémon when between 10–20% HP, and would do so without fail, rather than roughly 25% of the time.

Looking at the code, it looks like the lines which are supposed to give her actions a 25% of happening is implemented incorrectly, so her actions actually happen 100% of the time (assuming HP conditions are met):

cp 25 percent + 1

should be followed by

ret nc

Perhaps some comments around this line could highlight that the 25% chance is effectively ignored?

On a separate note, she switched repeatedly and without fail until she first used a Hyper Potion, and then would never switch that Pokémon again. Perhaps some comments could be put in data/trainers/ai_pointers.asm indicating that the value given only refers to the number of **items** the Trainer can use per Pokémon, and doesn't account for switching?

**Comment by Rangi42** [comment]
This kind of overlaps with #258: Gen 1 had a *lot* of bugs that could use documenting. Some of them have related comments in the source code already, like for Missingno, but there's no equivalent yet of pokecrystal's [`bugs_and_glitches.md`](https://github.com/pret/pokecrystal/blob/master/docs/bugs_and_glitches.md) (which lists 72 bugs and their fixes, with a couple more having still-open todo issues).

**Comment by coltongit** [comment]
I'll be adding a wiki tutorial with this fix to the wiki articles in the morning

**Comment by Rangi42** [comment]
> I'll be adding a wiki tutorial with this fix to the wiki articles in the morning

This issue is closed, and the wiki is free for anyone to edit without needing discussion and review and high standards for editing. Just go ahead and do it whenever.

**Comment by dannye** [comment]
Not only is the "status update" comment not necessary as Rangi pointed out, but it isn't even an update on anything actual.
It's just a statement of something you hope to do in the future. This is unhelpful.
