### ISSUE TITLE
Pokemon Red but in python?

### ISSUE THREAD

**Issue by MonkeyToiletLadder** [pret/pokered#314]
Hello.  Im trying to write a clone of pokemon red in python.  Would it be silly of me to try and make the code based off of the data structures in your asm?  Like i want to have glitches included but it seems like this might not be possible in python since its not a memory managed language.  Thanks from vaxeral.

**Comment by CelestialAmber** [comment]
This isn't really the proper place to ask about that. There's a pret Discord server which would be a better place to ask questions like that: https://discord.gg/d5dubZ3
