### ISSUE TITLE
you forgot to lock the other ones silly

### ISSUE THREAD

**Issue by luigismanslave** [pret/pokered#341]
im not a pedophile and the argument that hating something means you wanna fuck it is brainlet tier. the death penalty should be reserved exclusively for pedophiles (like ax6 and red)

![6a00d83452033569e201b7c8666ac8970b-350wi](https://user-images.githubusercontent.com/43482328/140575890-01db1ce8-0fc5-4416-b2f1-44b61b796826.png)

**Comment by Asday** [comment]
Dude I fucking love video games.

**Comment by luigismanslave** [comment]
me too friend

**Comment by luigismanslave** [comment]
fuck you pikalax, red defender ass lmao
