### ISSUE TITLE
Visual Studio

### ISSUE THREAD

**Issue by faspiller** [pret/pokered#345]
Is it possible to build the assembly project in MS Visual Studio without having to go through the long and tedious process installing a Linux virtual machine that'll take space and I'll probably never need otherwise?
I tried creating a C++ project, adding the ASM files and building it: it looked like it worked, but it didn't compile due to "not being able to open" files with the INCLUDE command (fatal error A1000).

**Comment by dannye** [comment]
To assemble the project you need to install the rgbds assembler. Then you need to build the project according to the Makefile. You don't *have* to use a Linux virtual machine or WSL. You can use cygwin or msys2.

**Comment by faspiller** [comment]
> To assemble the project you need to install the rgbds assembler. Then you need to build the project according to the Makefile. You don't _have_ to use a Linux virtual machine or WSL. You can use cygwin or msys2.

I will try immediately, thank you!
