### ISSUE TITLE
License

### ISSUE THREAD

**Issue by throwaway1037** [pret/pokered#347]
Please may the project be released under a [libre license](https://gnu.org/licenses/license-list.html)?

This would be completely legal, as this is a clean room reverse engineering project.

(Obligatory I am not a lawyer.)

**Comment by aaaaaa123456789** [comment]
This is not clean room, as it is a matching disassembly: it derives from the original binary.
Nobody here can license it.

**Comment by throwaway1037** [comment]
I apologise; I was mistaken; it is not a clean room project.

However, I think it might still be legal to license it somehow.

**Comment by aaaaaa123456789** [comment]
It is not.

**Comment by throwaway1037** [comment]
Are you a lawyer?

**Comment by aaaaaa123456789** [comment]
I'm not. I've just read enough about the topic. And besides, I'm definitely not a lawyer _from your country_, which is what you'd need to find if _you_ wanted to relicense anything.
That being said, the matter here is obviously clear-cut to anyone who has read about the topic, so I recommend you just look up how derivative works work.

**Comment by throwaway1037** [comment]
I was under the impression that reverse-engineered code, at least in the US, is not covered under copright law and as such is not considered a derivative, although other laws such as patent law may still cover the resulting reverse-engineered code.

**Comment by aaaaaa123456789** [comment]
And where would you get that impression from? As far as the US goes, there's a bit of case law about reverse engineering for specific purposes (compatibility, for instance), but those are limited exceptions.

**Comment by throwaway1037** [comment]
I seem to recall that many popular programs are reverse-engineered clones.

**Comment by aaaaaa123456789** [comment]
There's a difference between reverse-engineering and reimplementing functionality and reconstructing the original code of something.

**Comment by throwaway1037** [comment]
Yet our unjust laws allow one and prevent the other.

**Comment by aaaaaa123456789** [comment]
I'm personally against copyright in general, but our opinions don't change the legal status of anything. That's not how laws work.

**Comment by throwaway1037** [comment]
How unfortunate and undemocratic.

**Comment by Asday** [comment]
I have a feeling @throwaway1037 glows in the dark.

You don't get to walk into a discussion and say "I think it might still be legal", then when someone tells you a fact respond with "are you a lawyer?"

**Comment by throwaway1037** [comment]
You do if you were wrong and apologised for it.
