### ISSUE TITLE
Compile Yellow.

### ISSUE THREAD

**Issue by yenatch** [pret/pokered#36]

**Comment by mathiasbynens** [comment]
Current build output:

```bash
$ make yellow
rgbasm -h -o yellow/audio.o yellow/audio.asm
rgbasm -h -o yellow/main.o yellow/main.asm
rgbasm -h -o yellow/text.o yellow/text.asm
rgbasm -h -o yellow/wram.o yellow/wram.asm
rgblink -n pokeyellow.sym -o pokeyellow.gbc yellow/audio.o yellow/main.o yellow/text.o yellow/wram.o
rgblink: Unknown symbol 'SPRITE_JAMES'
make: *** [pokeyellow.gbc] Error 1
```

**Comment by angrybanana** [comment]
We're missing over world sprites for Jessie and James.

**Comment by dannye** [comment]
https://github.com/Sanqui/pokered-randomizer/pull/18
https://github.com/dannye/pokeyellow/blob/master/gfx/sprites/jessie.png
https://github.com/dannye/pokeyellow/blob/master/gfx/sprites/james.png

**Comment by angrybanana** [comment]
Dannye I'm guessing you ran into the new error "unknown symbol 'wcd13'"
To remedy we'll need to edit ~/pokered/text.asm
Look for 
_AfterTrade2Text:: ; a8212 (2a:4212)
IF DEF(_YELLOW)
	text "Hello there! Your"
	line "old @"
	TX_RAM wcd13
	db " is"
	cont "magnificent!"
ELSE

Edit wcd13 to wInGameTradeGiveMonName

**Comment by dannye** [comment]
https://github.com/yenatch/pokered/commit/2d319f1dd35b0e2dc134ad8be1cb6b376b849522

**Comment by yenatch** [comment]
https://github.com/luckytyphlosion/pokeyellow
