### ISSUE TITLE
Comment the wave pattern 5 data that happens to be read from SFX

### ISSUE THREAD

**Issue by Rangi42** [pret/pokered#402]

**Comment by dannye** [comment]
For Lavender:
```
db  2,  1, 14,  2,  3,  3,  2,  8, 14,  1,  2,  2, 15, 15, 14, 10,  1,  0,  1,  4, 13, 12,  1,  0, 14,  3,  4,  1,  5,  1,  7,  3
```

For Pokemon Tower:
```
db  2,  1, 14,  2,  3,  3,  2,  8, 14,  1,  2,  2, 15, 15,  2,  2, 15,  7,  2,  4,  2,  2, 15,  7,  3,  4,  2,  4, 15,  7,  4,  4
```

**Comment by Rangi42** [comment]
Lavender is "Music 1"; looks like the wave pattern 5 is the same in "Music 3", although no song in there uses it.

**Comment by dannye** [comment]
No, [pokemon tower is in music 3](https://github.com/pret/pokered/blob/master/audio.asm#L438)

**Comment by Rangi42** [comment]
Oops, yeah; and I missed that 1 has pokeflute.asm in between the start menu and cut SFX, but 3 doesn't. So all three are different.
