### ISSUE TITLE
UndergroundPathNorthSouth.blk doesn't work with PolishedMap

### ISSUE THREAD

**Issue by JuniorJedi490** [pret/pokered#442]
Based on a couple tutorials and the most recent commit to the map .blk files, it looks like all the .blk files are meant to be readable and editable using PolishedMap.
I can open every map in the game with PolishedMap (having recently done so in order to grab screenshots), except for UndergroundPathNorthSouth.blk, which shows an error saying the file ends early.
Attached is a screenshot of my PolishedMap window showing the error.
![Screenshot 2023-12-12 185605](https://github.com/pret/pokered/assets/61092338/cea0bafb-2767-489b-a18f-48ab7bff199d)

**Comment by dannye** [comment]
That's because the dimensions of the map are specified incorrectly in the game.

See https://github.com/pret/pokered/blob/f6017dd/constants/map_constants.asm#L141:
```
map_const UNDERGROUND_PATH_NORTH_SOUTH,   4, 24 ; $77 ; UndergroundPathNorthSouth.blk is actually 4x23
```

If you change this line to use 23 instead of 24, it opens correctly in Polished Map.

**Comment by JuniorJedi490** [comment]
Found another workaround that doesn't involve editing files
![Screenshot 2023-12-12 191046](https://github.com/pret/pokered/assets/61092338/ebe04c38-d7c6-4ec3-9417-7d2dae0a8acc)

**Comment by dannye** [comment]
Oh nice, I didn't notice that option was there. Neat!
