### ISSUE TITLE
decomposition into files of another version

### ISSUE THREAD

**Issue by sangacanga1** [pret/pokered#477]
Hello. On this site there are English versions of the original Japanese versions of the 1st generation games. Is there any way to separate these versions into their files using your method?

https://www.pokecommunity.com/threads/pocketrgb-en-a-full-red-green-and-blue-translation-of-the-original-pocket-monsters.492958/

**Comment by Rangi42** [comment]
There's a [pokered-jp](https://github.com/luckytyphlosion/pokered-jp) project but it hasn't been worked on in years and is far from complete. Disassembling a ROM hack is also possible; you can try using [mgbdis](https://github.com/mattcurrie/mgbdis), and see how the commit histories of other disassemblies from scratch (like [pokepicross](https://github.com/mid-kid/pokepicross) or [LADX](https://github.com/zladx/LADX-Disassembly)) have gone. The original [pokemon-reverse-engineering-tools](https://github.com/pret/pokemon-reverse-engineering-tools) used to help create pokecrystal and pokered are still available for reference, but are unlikely to be useful as-is; you have your own needs for this ROMhack and better tools could be made using what we know now anyway.
