### ISSUE TITLE
split up and group related wram/rom sections

### ISSUE THREAD

**Issue by yenatch** [pret/pokered#77]
Find a way to arrange disorganized sections in the same order as the baserom.
- Is this feasible when rgblink only cares about the order objects and sections are read?
- Will it even be any easier to manage if rgblink is changed to sort sections by some other method?

Section prototypes were proposed in the past. Example:

``` asm
section "first", wram0
section "second", wram0

section "main", rom0
    dw wSecond, wFirst

section "second", wram0
wSecond:
    ds 10

section "first", wram0
wFirst:
    ds 10
```

outputs

```
c00a c000
```

This method works already within an object, but rgblink considers one object at a time when determining section placement, even if both sections are declared in both objects.

**Comment by Sanqui** [comment]
Since ROM sections are now all hardcoded and will stay like that as long as `rgbds`'s section placement is "arbitrary", I'll close this issue unless there's something specific to be done.
