### ISSUE TITLE
style guide

### ISSUE THREAD

**Issue by yenatch** [pret/pokered#91]

**Comment by PikalaxALT** [comment]
Issue is open but with no description or elaboration on record from the original poster.

**Comment by Sanqui** [comment]
Well, it is self-explanatory.  We could use a style guide.

**Comment by kanzure** [comment]
Usually this is a `CONTRIBUTING.md` file.

**Comment by huderlem** [comment]
I've been thinking that building a linter for rgbds would be an interesting project.  Then it's easy to enforce style, although it seems a bit overkill.  Probably just a nice-to-have.

**Comment by Rangi42** [comment]
pokecrystal's [STYLE.md](https://github.com/pret/pokecrystal/blob/master/STYLE.md) and [code cleanup](https://github.com/pret/pokecrystal/wiki/Code-cleanup) wiki page apply to all the Gen 1+2 repos.
